apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flowpulse.fullname" . }}-aggregator
  namespace: {{ include "flowpulse.namespace" . }}
  labels:
    {{- include "flowpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flowpulse.name" . }}-aggregator
      {{- include "flowpulse.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flowpulse.fullname" . }}-server
  namespace: {{ include "flowpulse.namespace" . }}
  labels:
    {{- include "flowpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flowpulse.name" . }}-server
      {{- include "flowpulse.selectorLabels" . | nindent 6 }}
