apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowpulse.secretName" . }}
  namespace: {{ include "flowpulse.namespace" . }}
  labels:
    {{- include "flowpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  clickhouse-dsn: {{ include "flowpulse.clickhouse.dsn" . | quote }}
  nats-url: {{ include "flowpulse.nats.url" . | quote }}
  redis-addr: {{ include "flowpulse.redis.addr" . | quote }}
  jwt-secret: {{ .Values.auth.jwtSecret | default (randAlphaNum 64) | quote }}
  {{- if .Values.smtp.enabled }}
  smtp-host: {{ .Values.smtp.host | quote }}
  smtp-port: {{ .Values.smtp.port | quote }}
  smtp-user: {{ .Values.smtp.user | quote }}
  smtp-pass: {{ .Values.smtp.pass | quote }}
  alert-from: {{ .Values.smtp.from | quote }}
  alert-recipients: {{ .Values.smtp.recipients | quote }}
  {{- end }}
