apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowpulse.fullname" . }}-agent
  namespace: {{ include "flowpulse.namespace" . }}
  labels:
    {{- include "flowpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowpulse.fullname" . }}-aggregator
  namespace: {{ include "flowpulse.namespace" . }}
  labels:
    {{- include "flowpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowpulse.fullname" . }}-server
  namespace: {{ include "flowpulse.namespace" . }}
  labels:
    {{- include "flowpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
